# Generated by Django 2.1.7 on 2019-03-16 18:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('symptoms_description', models.CharField(blank=True, max_length=1000)),
                ('diagnosis', models.CharField(default='None', max_length=2000)),
                ('diagnosis_icd10', models.CharField(default='None', max_length=150)),
                ('examination_description', models.CharField(default='None', max_length=5000)),
                ('medication', models.CharField(blank=True, max_length=500)),
                ('medication_side_effects', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(blank=True, default='None', max_length=150)),
                ('related_to', models.CharField(choices=[('Appointment', 'Appointment'), ('Surgery', 'Surgery')], default='', max_length=12)),
                ('upload', models.FileField(upload_to='exam_files/')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(null=True)),
                ('social_security_number', models.CharField(max_length=11, unique=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('insurance', models.CharField(blank=True, max_length=100)),
                ('blood', models.CharField(choices=[('Ο-', 'Ο-'), ('Ο+', 'Ο+'), ('Α-', 'Α-'), ('Α+', 'Α+'), ('Β-', 'Β-'), ('Β+', 'Β+'), ('ΑΒ-', 'ΑΒ-'), ('ΑΒ+', 'ΑΒ+')], default='', max_length=3)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('procedure_description', models.CharField(blank=True, max_length=5000)),
                ('result_description', models.CharField(blank=True, max_length=5000)),
                ('medication', models.CharField(blank=True, max_length=500)),
                ('side_effects', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.BooleanField(default=False)),
                ('specialty', models.CharField(choices=[('Accident and Emergency Medicine', 'Accident and Emergency Medicine'), ('Allergiology', 'Allergiology'), ('Anesthetics', 'Anesthetics'), ('Cardiology', 'Cardiology'), ('Child Psychiatry', 'Child Psychiatry'), ('Clinical Biology', 'Clinical Biology'), ('Clinical Chemistry', 'Clinical Chemistry'), ('Clinical Neurophysiology', 'Clinical Neurophysiology'), ('Dental Oral Maxillo-facial surgery', 'Dental, Oral and Maxillo-facial Surgery'), ('Dermato-Venereology', 'Dermato-Venereology'), ('Dermatology', 'Dermatology'), ('Endocrinology', 'Endocrinology'), ('Family and general Medicine', 'Family and General Medicine'), ('Fictional Medical Specialist', 'Fictional Medical Specialist'), ('Gastro-enterologic Surgery', 'Gastro-enterologic Surgery'), ('Gastroenterology', 'Gastroenterology'), ('General Hematology', 'General Hematology'), ('General Practice', 'General Practice'), ('General Surgery', 'General Surgery'), ('Geriatrics', 'Geriatrics'), ('Immunology', 'Immunology'), ('Infectious Diseases', 'Infectious Diseases'), ('Internal Medicine', 'Internal Medicine'), ('Laboratory Medicine', 'Laboratory Medicine'), ('Maxillo-facial Surgery', 'Maxillo-facial Surgery'), ('Microbiology', 'Microbiology'), ('Nephrology', 'Nephrology'), ('Neuro-psychiatry', 'Neuro-psyciatry'), ('Neurosurgery', 'Neurosurgery'), ('Nuclear Medicine', 'Nuclear Medicine'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'), ('Occupational Medicine', 'Occupational Medicine'), ('Opthalmology', 'Ophtalmology'), ('Orthopaedics', 'Orthopaedics'), ('Otorhinolaryngology', 'Otorhinolaryngology'), ('Paediatrics', 'Paediatrics'), ('Paediatrics Surgery', 'Paediatrics Surgery'), ('Pathology', 'Pathology'), ('Physical Medicine and Rehabilitation', 'Physical Medicine and Rehabilitation'), ('Plastic Surgery', 'Plastic Surgery'), ('Pneumology', 'Pneumology'), ('Podiatric Surgery', 'Podiatric Surgery'), ('Psychiatry', 'Psychiatry'), ('Public health and Preventive Medicine', 'Public Health and Preventive Medicine'), ('Radiation Oncology', 'Radiation Oncology'), ('Respiratory Medicine', 'Respiratory Medicine'), ('Rheumatogoly', 'Rheumatology'), ('Stomatology', 'Stomatology'), ('Thoragic Surgery', 'Thoragic Surgery'), ('Tropical Medicine', 'Tropical Medicine'), ('Urology', 'Urology'), ('Vascular Surgery', 'Vascular Surgery'), ('Venereology', 'Venereology')], default='General_Practice', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('side_effects', models.CharField(blank=True, max_length=1000)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.UserProfile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.PatientProfile')),
            ],
        ),
        migrations.AddField(
            model_name='surgery',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.UserProfile'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.PatientProfile'),
        ),
        migrations.AddField(
            model_name='exam_files',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.UserProfile'),
        ),
        migrations.AddField(
            model_name='exam_files',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.PatientProfile'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.UserProfile'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.PatientProfile'),
        ),
    ]
