# Generated by Django 2.1.7 on 2019-03-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_files',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='exam_files',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Exam_files',
        ),
    ]
