# Generated by Django 2.1.7 on 2019-03-16 18:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0002_auto_20190316_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(blank=True, default='None', max_length=150)),
                ('related_to', models.CharField(choices=[('Appointment', 'Appointment'), ('Surgery', 'Surgery')], default='', max_length=12)),
                ('upload', models.FileField(upload_to='exam_files/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.UserProfile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.PatientProfile')),
            ],
        ),
    ]
