# Generated by Django 2.1.7 on 2019-03-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0004_auto_20190320_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='doctor',
        ),
    ]
