# Generated by Django 2.1.7 on 2019-03-23 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0005_remove_userprofile_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='exam_files/')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.Appointments')),
            ],
        ),
        migrations.RemoveField(
            model_name='exam_files',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='exam_files',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Exam_files',
        ),
    ]
