# Generated by Django 2.1.7 on 2019-05-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0010_app_icd10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='specialty',
            field=models.CharField(choices=[('Accident_and_Emergency_Medicine', 'Accident and Emergency Medicine'), ('Allergiology', 'Allergiology'), ('Anesthetics', 'Anesthetics'), ('Cardiology', 'Cardiology'), ('Child_Psychiatry', 'Child Psychiatry'), ('Clinical_Biology', 'Clinical Biology'), ('Clinical_Chemistry', 'Clinical Chemistry'), ('Clinical_Neurophysiology', 'Clinical Neurophysiology'), ('Dental_Oral_Maxillo-facial_surgery', 'Dental, Oral and Maxillo-facial Surgery'), ('Dermato-Venereology', 'Dermato-Venereology'), ('Dermatology', 'Dermatology'), ('Endocrinology', 'Endocrinology'), ('Family_and_general_Medicine', 'Family and General Medicine'), ('Fictional_Medical_Specialist', 'Fictional Medical Specialist'), ('Gastro-enterologic_Surgery', 'Gastro-enterologic Surgery'), ('Gastroenterology', 'Gastroenterology'), ('General_Hematology', 'General Hematology'), ('General_Practice', 'General Practice'), ('General_Surgery', 'General Surgery'), ('Geriatrics', 'Geriatrics'), ('Immunology', 'Immunology'), ('Infectious_Diseases', 'Infectious Diseases'), ('Internal_Medicine', 'Internal Medicine'), ('Laboratory_Medicine', 'Laboratory Medicine'), ('Maxillo-facial_Surgery', 'Maxillo-facial Surgery'), ('Microbiology', 'Microbiology'), ('Nephrology', 'Nephrology'), ('Neuro-psychiatry', 'Neuro-psyciatry'), ('Neurosurgery', 'Neurosurgery'), ('Nuclear_Medicine', 'Nuclear Medicine'), ('Obstetrics_and_Gynecology', 'Obstetrics and Gynecology'), ('Occupational_Medicine', 'Occupational Medicine'), ('Opthalmology', 'Ophtalmology'), ('Orthopaedics', 'Orthopaedics'), ('Otorhinolaryngology', 'Otorhinolaryngology'), ('Paediatrics', 'Paediatrics'), ('Paediatrics_Surgery', 'Paediatrics Surgery'), ('Pathology', 'Pathology'), ('Physical_Medicine_and_Rehabilitation', 'Physical Medicine and Rehabilitation'), ('Plastic_Surgery', 'Plastic Surgery'), ('Pneumology', 'Pneumology'), ('Podiatric_Surgery', 'Podiatric Surgery'), ('Psychiatry', 'Psychiatry'), ('Public_health_and_Preventive_Medicine', 'Public Health and Preventive Medicine'), ('Radiation_Oncology', 'Radiation Oncology'), ('Respiratory_Medicine', 'Respiratory Medicine'), ('Rheumatogoly', 'Rheumatology'), ('Stomatology', 'Stomatology'), ('Thoragic_Surgery', 'Thoragic Surgery'), ('Tropical_Medicine', 'Tropical Medicine'), ('Urology', 'Urology'), ('Vascular_Surgery', 'Vascular Surgery'), ('Venereology', 'Venereology')], default='General_Practice', max_length=100),
        ),
    ]
