# Generated by Django 2.1.7 on 2019-05-23 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0012_auto_20190521_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('confirmed', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.UserProfile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.PatientProfile')),
            ],
        ),
    ]
