# Generated by Django 2.1.7 on 2019-05-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0013_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='event',
            name='patient',
        ),
    ]
