# Generated by Django 2.1.7 on 2019-05-23 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0014_auto_20190523_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mr.UserProfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mr.PatientProfile'),
        ),
    ]
