# Generated by Django 2.1.7 on 2019-06-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0015_auto_20190523_1221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='openinghours',
            unique_together={('doctor', 'day', 'from_hour', 'to_hour')},
        ),
    ]
