# Generated by Django 2.1.7 on 2019-06-08 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0016_auto_20190605_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.UserProfile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.PatientProfile')),
            ],
        ),
    ]
