# Generated by Django 2.1.7 on 2019-06-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0018_appointments_secret_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='secret_note',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='secret_note',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
