# Generated by Django 2.1.7 on 2019-06-17 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0019_auto_20190609_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgery_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='exam_files/')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.Surgery')),
            ],
        ),
    ]
